### ISSUE TITLE
AnalyticsData runRealTimeReport responds with 404 URL not found on this server

### ISSUE THREAD

**Issue by bramvandooren** [googleapis/google-api-php-client-services#1502]
When trying to use `\Google\Service\AnalyticsData\Resource\Properties::runRealtimeReport` it responds with a 404 error stating the requested URL is not found on this server.

It uses this URL:
`https://analyticsdata.googleapis.com/v1beta/<propertyID>:runRealtimeReport` 

It works if it is changed to:
`https://analyticsdata.googleapis.com/v1beta/properties/<propertyID>:runRealtimeReport `

https://github.com/googleapis/google-api-php-client-services/blob/efb828fa75a3a3dccd3ffdf8595624af365ac35b/src/AnalyticsData.php#L119

**Comment by bshaffer** [comment]
Hello @bramvandooren !

This is because the "property" field uses the format `property/<property-id>`, and is documented in the function call for `Google\Service\AnalyticsData\Resource\Properties::runRealTimeReport` here: https://github.com/googleapis/google-api-php-client-services/blob/main/src/AnalyticsData/Resource/Properties.php#L173-L180
