### ISSUE TITLE
Wrong `collection_key` in Google_Service_SQLAdmin_InstancesListResponse

### ISSUE THREAD

**Issue by emocharnik** [googleapis/google-api-php-client-services#169]
[This change](https://github.com/googleapis/google-api-php-client-services/commit/49208ebd8466573ba1adf8c425337efe2b1e05df#diff-bea6ccd3c08dda610ddc15322e345c35) might be a bug, because now if you try to iterate object which is returned by **\Google_Service_SQLAdmin_Resource_Instances::listInstances** it considered as empty. I'm aware of using **::getItems()** instead, but I'm afraid of other collections might have the same issue

#### Environment details
  - Package name and version: v0.99

**Comment by jdpedrie** [comment]
* [Relevant discovery document object](https://github.com/googleapis/discovery-artifact-manager/blob/master/discoveries/sqladmin.v1beta4.json#L887-L916)

**Comment by jdpedrie** [comment]
Thanks for the report @emocharnik. We'll look into it!

**Comment by emocharnik** [comment]
@jdpedrie any update on the issue?

**Comment by jdpedrie** [comment]
@emocharnik not as of yet. Since those classes are automatically generated, a fix will be rather difficult. We're discussing options, but for the time being, when in doubt, iterate over the result returned from the getter, as you mentioned, rather than over the response object itself.

Sorry for the inconvenience.

**Comment by holtkamp** [comment]
Maybe related to https://github.com/googleapis/google-api-php-client-services/issues/28#issuecomment-314583187

**Comment by dwsupplee** [comment]
It looks as though the response here contains two array types, `warnings` and `items`.

Unfortunately, the code generator makes an assumption a single `array` type will be in a response and uses this information to determine the `collection_key`. This key is then used in the `Iterator` interface implementation used by our collection based classes. There isn't a mechanism in the discovery API to dictate which `array` item should favored to iterate over, so it seems the best path forward here is to remove the `Iterator` interface from the collections. Another option would be to prefer an `items` array over any others, but this wouldn't be completely reliable as the `items` key doesn't appear to be consistently used.

Since removing the `Iterator` interface would be breaking most responses do only have a single `array` type I'd like to hold off on doing this. Instead I'd like to recommend to any new users that you explicitly use getters (`getItems()`, etc.) over the methods exposed by the `Interator` interface.
