### ISSUE TITLE
Tag Manager API v2 has a missing method

### ISSUE THREAD

**Issue by Generation4** [googleapis/google-api-php-client-services#176]
Hi,
On Tag Manager API v2 there is no 'create' method for 'Container Version' (exists only in API v1).
There is a way in API v2 to create 'Container Version' without 'create' method?

Thank You!

**Comment by jdpedrie** [comment]
Hi @Generation4,

Looks like you posted about this on the [community support site](https://support.google.com/tagmanager/thread/10928107?hl=en) as well. That is the best place for this. I reviewed the API and it does seem that v2 is missing a way to create a Container Version. However, this repository only provides generated code based off of the API specification published by the product team, so we're unfortunately not able to address this issue here.

Please let us know if you run into any issues with the client itself and we'd be happy to help. Best of luck!

**Comment by Generation4** [comment]
@jdpedrie Thank you for your answer!
For future readers: I got the answer that in API v2 the creation of versions is from Workspaces: create_version.
