### ISSUE TITLE
Could not found a way to retrieve business profile reviews using business profile

### ISSUE THREAD

**Issue by engrsandeep** [googleapis/google-api-php-client-services#2122]
Hi,

I was building a review system, i am to get business accounts and locations, but could not found a way to retrieve reviews.

Not able to access to V4 api as getting below message even thought Google My Business API  is working fine to get accounts, locations and other features. Can you please help ?

Google My Business API has not been used in project 973507770112 before or it is disabled.

**Comment by bizmate** [comment]
As per message *you need to enable the API*, follow documentation online as this repository is not for Google MyBusiness API issues but it is just generic. Just Google it and you will find the documentation

**Comment by engrsandeep** [comment]
API is already enabled thats why able to access accounts and locations endpoints. but did not see any option to get reviews in latest API, but when try with old API it do not allow.

**Comment by ConnectGrid** [comment]
@engrsandeep 

I feel your pain! I'm creating a reviews app that needs to fetch Business Reviews. It has literally taken me -weeks- to work through the documentation and make any sense of it. I've been going in so many circles, I'm dizzy!

Some takeaways that may help:

1. The old MyBusiness API is v4.x, and the new "Business Profiles" API is v1.0 or v1.1, depending on which service that you are looking at. Why would they go *backwards* in version numbers? This threw me for a loop! And even though they are renaming the API, they still call it "MyBusiness" throughout the documentation and APIs. Just adds to the confusion.

2. The API methods that you need are spread across multiple *services*. For example, accessing Accounts is in the `MyBusinessAccountManagement` service, whereas business location data is in the `MyBusinessBusinessInformation` service. I struggled to get account details because I was using the wrong service, but you need the "account name" in order to get business locations.

You would think if they were going through the massive effort of introducing new, modern API, they would spend a bit more effort cleaning it up. Terms like "Business", "Profile", "Account", "Listings" can sometimes be used interchangeably, but often can not be. Reading the docs multiple times brings some clarity (eventually).

In my application, I actually created a mock `AccountManagement` service (as a replacement of `MyBusinessAccountManagement`) because technically Google Accounts are separate from Business Management, so it makes sense to have this as a separate, independent API service, not within the MyBusiness / Business Profiles API. Why they bundle it in this one API is bizarre and illogical. Other APIs seem to have their own separate ways of accessing accounts, and this duplication/redundancy just makes our job harder.

Hopefully this info helped a bit. It's definitely not an easy task getting everything set up and working. Keep at it.

**Comment by engrsandeep** [comment]
@ConnectGrid Thanks for understanding :) even though documents are not properly updated. 
Yes i am able to access Accounts and Locations with MyBusinessAccountManagement and MyBusinessBusinessInformation but there is no option to get reviews in new api. it is there in v4.x but when i try to use v4.x then it says *Google My Business API has not been used or disabled*

**Comment by ConnectGrid** [comment]
This page may have the answer for you:
https://stackoverflow.com/questions/71953312/google-my-business-api-has-not-been-used-in-project-projectnumber

> Reviews are currently only available through a 9th API that you have not enabled:
> 
> The [Google My Business API v4.9](https://developers.google.com/my-business/reference/rest).

On my API list, that particular API has a label of "Private" next to it. The others do not, so not sure what is special about it.

**Comment by engrsandeep** [comment]
@ConnectGrid Thank you. it is working now.
