### ISSUE TITLE
(YouTube) 404 error since 0.147

### ISSUE THREAD

**Issue by ThibaultVlacich** [googleapis/google-api-php-client-services#217]
In commit 971e24d714dbd1a0673c1d8b2595662bd1c67d0c, the base URL for YouTube was changed from www.googleapis.com to youtube.googleapis.com ([direct link to change](https://github.com/googleapis/google-api-php-client-services/commit/971e24d714dbd1a0673c1d8b2595662bd1c67d0c#diff-9631397405c271c00f52394f814cdc19R96))

Since this commit, that was published with version 0.147, requests are 404ing.

**Comment by jdpedrie** [comment]
Hi @ThibaultVlacich,

I'm sorry you're having this issue. For the moment, I suggest pinning to `v0.146`. Since this library is auto-generated, we don't have much control over changes here. I suggest opening an issue on the [public issue tracker](https://issuetracker.google.com/issues?q=componentid:186600). Reference this issue and the corresponding [service schema](https://github.com/googleapis/discovery-artifact-manager/blob/master/discoveries/youtube.v3.json#L3800).

**Comment by ThibaultVlacich** [comment]
Thanks, I opened an issue and looks like this was fixed in upstream.
I'll close this issue when it will be released.

**Comment by ThibaultVlacich** [comment]
Fixed in https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.148
