### ISSUE TITLE
Consider publishing each service as a separate package

### ISSUE THREAD

**Issue by perifer** [googleapis/google-api-php-client-services#222]
Citing https://github.com/googleapis/google-api-php-client#cleaning-up-unused-services

> There are over 200 Google API services. The chances are good that you will not want them all. In order to avoid shipping these dependencies with your code, you can run the Google\Task\Composer::cleanup ...

My guess is that most developers don't read this and ship their code with all services. 

Furthermore, Packagist currently states 29 365 181 installs. The package is around 13 MB zipped. That is a lot of wasted bandwidth. Considering both the time spent downloading this code on CI-servers and developing machines as well as the environmental impact this brings, a better option might be to publish each service as a separate package?

Both Symfony and Laravel have mono-repos but publish the code as individual packages, so it can be done. E.g https://github.com/symfony/symfony/tree/5.x/src/Symfony/Component/CssSelector which is published as https://packagist.org/packages/symfony/css-selector

**Comment by mfn** [comment]
Especially this note sounds pretty dangerous, manually mucking around with vendor/
> IMPORTANT: If you add any services back in composer.json, you will need to remove the vendor/google/apiclient-services directory explicity for the change you made to have effect:

OTOH I can also imagine what happens next: people won't realize this and than complain they're missing the services. Ok, I was a bit kidding here.

Explicitly stating the dependent services would be very good IMHO too.

**Comment by bshaffer** [comment]
Any deployment process *should* install vendors as part of the build process. This note is mostly for development. I cannot think of a situation that could be called "dangerous". The issue here is frustration and time lost by developers who don't know why their API classes aren't loading.

It would be really great to have individual packages for this, and but until packagist allows us to do multiple packages in one github repo (not likely) or we come up with some other solution, we won't get there any time soon. We will not be able to maintain 200+ repositories and packages for this client library. 

The https://github.com/googleapis/google-cloud-php client libraries do have individual packages, and this is the way we are going (one API at a time) for all Google API clients. Hopefully we can release many clients like this in the near future.

**Comment by perifer** [comment]
@bshaffer did you see my comment above?

>  Both Symfony and Laravel have mono-repos but publish the code as individual packages, so it can be done. E.g https://github.com/symfony/symfony/tree/5.x/src/Symfony/Component/CssSelector which is published as https://packagist.org/packages/symfony/css-selector

I don't know how those projects are setup but I can do some research if that would help this issue going forward.

**Comment by jdpedrie** [comment]
As you can see, [`symfony/css-selector`](https://github.com/symfony/css-selector) is published to packagist from a separate repository. Like @bshaffer mentioned above, [Google Cloud PHP](https://github.com/googleapis/google-cloud-php) does the same with its packages, for instance [`google/cloud-pubsub`](https://github.com/googleapis/google-cloud-php-pubsub). The requirement for a repository for each split service introduces a maintenance burden which is difficult to overcome for the large number of services contained in this library. It's certainly something we're very aware of and for which we are actively trying to find solutions.

**Comment by perifer** [comment]
I see! Thanks for the clarification.

**Comment by bshaffer** [comment]
Closing as WAD as we are aware of the issue. Thank you for submitting this!
