### ISSUE TITLE
Package is difficult to install

### ISSUE THREAD

**Issue by chibyk101** [googleapis/google-api-php-client-services#3398]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-php-client-services/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+php

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Windows 10/CentOS 7
  - PHP version: 8.1
  - Package name and version: google/apiclient-services

#### Steps to reproduce

  1. composer install google/apiclient-services
This packages stays for 15min and times out. could never get installed. propbably the bundle size is too large

**Comment by vishwarajanand** [comment]
Specifically for the timeout issue, its happening due to intermittent network at your end. Package size has little to do for that.

BTW, the package size is ~120 MB and it took a few seconds for me to install. Its fairly large because it has source to connect to ~300 different google services.

<details>

<pre>
Desktop mkdir -p Test                 
➜  Desktop cd Test     
➜  Test nano composer.json     
➜  Test time (composer require google/apiclient-services)
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php:879
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php:884
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^0.316.0 for google/apiclient-services
./composer.json has been updated
Running composer update google/apiclient-services
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking google/apiclient-services (v0.316.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading google/apiclient-services (v0.316.0)
  - Installing google/apiclient-services (v0.316.0): Extracting archive
Generating autoload files
( composer require google/apiclient-services; )  2.20s user 1.97s system 80% cpu 5.169 total
➜  Test cat composer.json                  
{
    "require": {
        "google/apiclient-services": "^0.316.0"
    }
}
➜  Test ls
composer.json  composer.lock  vendor
➜  Test du -sh vendor                         
121M    vendor
➜  Test 
</pre>
</details>

**Comment by oliezekat** [comment]
> 120 MB (...) ~300 different google services

O__ô who believed is best practice ?
