### ISSUE TITLE
Send push notification to multiple device in single request

### ISSUE THREAD

**Issue by shriyank-vitec** [googleapis/google-api-php-client-services#3409]
```
$message = new Message([
            'notification' => $notification,
            'data' => $data,
            'token' => $token
        ]);
$request = new FirebaseCloudMessaging\SendMessageRequest();
$request->setMessage($message);


$messaging = new FirebaseCloudMessaging($this->client);
$response = $messaging->projects_messages->send('projects/my-project', $request);
```
        
I have implemented above code using FirebaseCloudMessaging (Laravel-PHP) but it send notification to one device at time. is there any way to send push notification to multiple device at once?

**Comment by vishwarajanand** [comment]
1. Seems like `MulticastMessage` and `sendMulticast` aren't there (since there's no official PHP Firebase Admin SDK), so you can either do that either via REST like how other language libraries are doing, [ref](https://firebase.google.com/docs/cloud-messaging/send-message#send-messages-to-multiple-devices).
2. Alternatively, you can send messages to a topic, via `setTopic` instead?

**Comment by shriyank-vitec** [comment]
@vishwarajanand Thank you for your reply, I removed library and  implemented REST API to send to multiple devices at same time.
