### ISSUE TITLE
Google Analytics Data APIs switch to v1beta breaks it

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [googleapis/google-api-php-client-services#345]
#### Environment details

  - OS: macOS Big Sur
  - PHP version: 7.4.18
  - Package name and version: v0.173.0 (google/apiclient:^2.9.1)

#### Steps to reproduce

  1. Set up google client and call the example V1Alpha code as shown in [the comment block](https://github.com/googleapis/google-api-php-client-services/blob/46b71684a100f3d976e0321cf24f487b314add68/src/Google/Service/AnalyticsData/Resource/V1alpha.php#L22-L23).

#### Code example

```php
$auth = ...content of downloaded google cloud .json key file...
$client = new Google_Client();
$client->setAuthConfig($auth);
$client->addScope(Google_Service_AnalyticsData::ANALYTICS_READONLY);

if ($client->isAccessTokenExpired()) {
    $client->refreshTokenWithAssertion();
}

$service = new Google_Service_AnalyticsData($client);
$v1alpha = $analyticsdataService->v1alpha;
```
Accessing v1alpha like that simply doesn't work and I get a `Undefined property: Google_Service_AnalyticsData::$v1alpha` error.

So I was using this API using v1alpha for several months and it worked totally fine until a couple of weeks ago. I used to use it like this:
```php
$requestData = [
    'entity' => [
        'propertyId' => $analyticsClient->propertyId
    ],
    'dateRanges' => [
        [
            'startDate' => $days.'daysAgo',
            'endDate'   => 'today'
        ]
    ],
    'orderBys' => $orderBys,
    'metrics' => $metrics,
    'dimensions' => $dimensions
];
$analyticsData = $analyticsClient->service->v1alpha->runReport(new Google_Service_AnalyticsData_RunReportRequest($requestData));
```

And it was working fine. Then I ran composer update and it seems to have updated the package. The class 'Google_Service_AnalyticsData' code seems to be changed internally to use v1beta. At first I thought just changing v1alpha to v1beta would do the trick but it didn't. I'm totally unable to use the v1alpha service and beta service doesn't have good enough code samples to work either.

**Comment by jdpedrie** [comment]
Hi @SaifurRahmanMohsin,

Sorry for the inconvenience! Since this library is auto-generated, this sort of thing can happen sometimes. You have a couple of options.

1. Add a specific version of `google/apiclient-services` to your composer.json `require`. It looks like `v0.171.0` would do the trick for you. The downside is you won't get updates for any services.
2. Switch to [`google/analytics-data`](https://packagist.org/packages/google/analytics-data). This is definitely the better option if it doesn't require rewriting a lot of your application!

As a general rule, I'd suggest before using `google/apiclient`, check if the API you need is available as a standalone package in [`google/cloud`](https://github.com/googleapis/google-cloud-php).

**Comment by SaifurRahmanMohsin** [comment]
@jdpedrie Yep, I ended up [switching to 0.169.0](https://github.com/mohsin/googleanalytics-plugin/commit/7dddf35ae95b5cc47b47239471b9c8c512d66860) to fix this temporarily. Will switch to beta eventually and hopefully stable once that's out. Thank you for the response.
