### ISSUE TITLE
API v0.20 is not fully backward compatible

### ISSUE THREAD

**Issue by dvesh3** [googleapis/google-api-php-client-services#383]
#### Environment details

  - OS: Any
  - PHP version: Any
  - Package name and version: v0.201.0

#### Description
Latest version `v0.201.0` is not fully backward compatible with changes from https://github.com/googleapis/google-api-php-client-services/pull/363. This breaks our code using old classname for API services e.g. `Google_Service_Customsearch`.

you can check our builds are failing with class not found error https://github.com/pimcore/pimcore/runs/2873257625 as it requires `google/apiclient:^2.8` which installs this version `google/apiclient-services`.

Any help would be greatly appreciated. thanks!

**Comment by holtkamp** [comment]
Apparently `https://github.com/googleapis/google-api-php-client-services/blob/v0.181.0/src/Google/Service/Customsearch.php` existed in `v0.181.0`, but was "dropped" in `v0.2.0`, this is strange indeed.

Additionally: I am not sure whether PHPStan as _static_ analyser is able to recognize the '_run-time_' approach to implement backwards compatibility using `class_alias()`

https://github.com/googleapis/google-api-php-client-services/blob/0375af405757b36f3bcc82e19d7daf61e0b4cfd8/src/CustomSearchAPI.php#L340

**Comment by dwsupplee** [comment]
@dvesh3 After digging in a bit it seems as though this removal was due to an update in the discovery document which [added a "canonical name" field](https://github.com/googleapis/discovery-artifact-manager/commit/b84b144958563a253508dd9ce85bfe933e430680?branch=b84b144958563a253508dd9ce85bfe933e430680&diff=split) for custom search. This caused the generator here to use the new name `CustomSearchAPI` instead of `Customsearch`. As one of the notes for v0.200.0 was `Removes all classes/services which no longer exist in the Discovery doc`, it must have been assumed the existing `Customsearch` directory was no longer valid.

Sorry about the trouble here, if you'd like to keep things working as-is you can pin to v0.181.0 - otherwise doing a search and replace for `Customsearch` -> `CustomSearchAPI` should do the trick as the interfaces should be pretty close to identical (I'd recommend this, as it will be the more "correct" approach since you'll get future updates to the interfaces since `Customsearch` is an un-updated artifact).
