### ISSUE TITLE
FirebaseRemoteConfig has been removed, possibly accidentally.

### ISSUE THREAD

**Issue by chasen** [googleapis/google-api-php-client-services#393]
As of 2.9.1 https://github.com/googleapis/google-api-php-client-services/tree/7272d5407ae281c67259c8997a3d481e0b26dc51/src/Google/Service/FirebaseRemoteConfig The FirebaseRemoteConfig still exists. However in 2.10.0 it was dropped without any deprecation.

Just wanted to check to see this was intentional before I went the route of switching to something else to interact with the API

**Comment by bshaffer** [comment]
Hello!
Yes, we changed which way we were generating these packages, and began using the services listed [here](https://github.com/googleapis/discovery-artifact-manager/tree/master/discoveries) instead of a different method which was much more brittle. 

Because of this, if you want any of those previous services you will need to pin to an older tagged version of this library (`google/apiclient-services`).
