### ISSUE TITLE
Documentation for the package says "updated daily", but as of today last update was 24 days ago

### ISSUE THREAD

**Issue by nekromoff** [googleapis/google-api-php-client-services#582]
So how is it?

**Comment by nekromoff** [comment]
![image](https://user-images.githubusercontent.com/8550349/149507065-ec271df2-0d81-4ba9-b138-17b75bff68af.png)

![image](https://user-images.githubusercontent.com/8550349/149507035-a4d9fe66-0f18-450e-b4bd-d8729fbbd82b.png)

**Comment by PaolaRuby** [comment]
> with new API changes

If there is no changes, what do you expect to get?, it's a bot searching daily for changes

**Comment by nekromoff** [comment]
There have been changes, e.g. Q&A was completely missing (but already in
the docs) when I posted the issue. It was only added 2 days ago. So,
clearly it does not happen daily.

**Comment by bshaffer** [comment]
@nekromoff, because of `Q&A` containing and ampersand in the name, it broke our builds and so everything was broken / not updating for 24 days. This is because 1. this library is in maintenance mode, 2. it happened over the holidays, and 3. I unfortunately didn't notice.

So, our apologies for not catching it sooner (although I am annoyed that someone thought adding an ampersand in a classname was okay)

**Comment by nekromoff** [comment]
Thank you for this explanation.
