### ISSUE TITLE
Service name inconsistency for "Bigquery" service.

### ISSUE THREAD

**Issue by juanparati** [googleapis/google-api-php-client-services#613]
#### Environment details

  - OS: MacOs or Linux with a case sensitive filesystem
  - PHP version: PHP 8.0
  - Package name and version: Bigquery

#### Problem explanation

It seems that many of the BigQuery services like "BigQueryConnectionService" and "BigQueryDataTransfer" are located into a directory that starts with the name "BigQuery" (Note that "Q" is uppercase) and the base "Bigquery" service has "q" in lowercase. It is in my opinion a name inconsistency that can arise some confusion with the service name when "google/apiclient-services" is used in composer.json.

#### Steps to reproduce

  1. Add "BigQuery" service to "google/apiclient-services"  in the composer.json. Example:
  
```
"extra": {
        "google/apiclient-services": [
            "BigQuery",
            "BigQueryConnectionService",
            "BigQueryDataTransfer"
        ]
    },
```
2. Execute composer install

#### Received result
`Google service "BigQuery" does not exist or was removed previously`

**Comment by bshaffer** [comment]
This is unfortunately Working As Designed because the [BigQuery discovery document](https://bigquery.googleapis.com/$discovery/rest?version=v2) does not include a "canonical name" as [BigQueryDataTransfer's discovery document](https://bigquerydatatransfer.googleapis.com/$discovery/rest?version=v1) does. 

One thing we could do is make the [composer cleanup task](https://github.com/googleapis/google-api-php-client/blob/main/src/Task/Composer.php) check case-insensitive. Feel free to submit a PR or file a feature request if you'd like to see this happen!
